language: ruby
before_script: support/arango.sh
script: 'bundle exec rake ci'
rvm:
  - 1.8.7
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode 
  - rbx-18mode
  - rbx-19mode
notifications:
  email:
    - mbj@seonic.net
